# Generated by Django 4.2.30 on 2026-07-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('walmart_week', models.CharField(max_length=6)),
                ('cutoff_at', models.DateTimeField()),
                ('prepared_by', models.CharField(default='Jessica', max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('READY', 'Ready for review'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cutoff_at'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_stock_id', models.CharField(max_length=80, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('walmart_item_number', models.CharField(blank=True, max_length=40)),
                ('all_links_item_number', models.CharField(blank=True, max_length=40)),
                ('consumer_id', models.CharField(blank=True, max_length=40)),
                ('gtin', models.CharField(blank=True, max_length=40)),
                ('pack_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vendor_stock_id'],
            },
        ),
        migrations.CreateModel(
            name='PackageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.PositiveSmallIntegerField(choices=[(1, 'Store Sales & Inventory'), (2, 'eCommerce Sales'), (3, 'eCommerce Inventory'), (4, 'Store Demand Forecast'), (5, 'Order Forecast'), (6, 'Confirmed POs, Receipts & OTIF'), (7, 'Factory Production & Finished Goods'), (8, 'Import, RJW Inventory & Shipments'), (9, 'Walmart Context & Exceptions')])),
                ('source_file', models.FileField(upload_to='sources/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('report_id', models.CharField(blank=True, max_length=120)),
                ('filters', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('POPULATED', 'Populated'), ('PARTIAL', 'Partial'), ('STALE', 'Requires refresh'), ('MISSING', 'Data missing'), ('ERROR', 'Validation error')], default='UPLOADED', max_length=14)),
                ('validation_message', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='controls.controlcycle')),
            ],
            options={
                'ordering': ['package_number', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('effect', models.TextField()),
                ('required_action', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('ACCEPTED', 'Accepted')], default='OPEN', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='controls.controlcycle')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controls.sku')),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_pos_units', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('store_pos_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('store_on_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('store_on_order', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('replen_instock', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('ecomm_units', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('ecomm_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('forecast_demand_4w', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('forecast_demand_13w', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('order_forecast_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('first_forecast_arrival', models.DateField(blank=True, null=True)),
                ('last_forecast_arrival', models.DateField(blank=True, null=True)),
                ('current_commitments', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('usable_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('confirmed_on_time_inbound', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('approved_buffer', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('projected_ending_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('projected_gap', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('decision_status', models.CharField(choices=[('BLOCKED', 'Blocked'), ('MONITOR', 'Monitor'), ('INVESTIGATE', 'Investigate'), ('RECOMMEND', 'Recommend'), ('RECORDED', 'Decision recorded')], default='BLOCKED', max_length=14)),
                ('recommendation', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='controls.controlcycle')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.sku')),
            ],
            options={
                'ordering': ['sku__vendor_stock_id'],
                'unique_together': {('cycle', 'sku')},
            },
        ),
    ]
