# Generated by Django 4.2.30 on 2026-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcycle',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='ecomm_available_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='factory_available_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='late_inbound_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_inbound_available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_mabd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='rjw_available_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
