# Generated by Django 4.2.30 on 2026-07-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_controlcycle_is_synthetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrow',
            name='actual_orders_l4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='ecomm_fc_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='ecomm_on_hand_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='ecomm_weeks_of_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='forecast_variance_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='forecast_variance_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='illustrative_initial_fill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='incremental_store_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='initial_fill_units_per_store',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='modular_set_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='modular_set_week',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_customs_clearance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_etd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_factory_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_factory_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='next_week_supply_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='otif_exception_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='otif_in_full_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='otif_on_time_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='prior_traited_store_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='rjw_allocated_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='rjw_held_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='rjw_physical_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='system_order_start_week',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='traited_store_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='work_in_process_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
